service: telegram-reminder

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2

functions:
  processEvent:
    handler: handler.processEvent
    url: true
    environment:
      BOT_API_KEY: "Enter bot api key"
      GROUP_CHAT_ID: "Enter group chat id"
      GOOGLE_SHEET_ID: "Enter GSheet Id"
      GID: 519871512
    events:
      - schedule: cron(0 16 ? * THU *)
